min_constraints_age <- c(318, 132.9, 108, 108, 120.7, 100.5, 125.0, 72.1, 37.8, 109, 87.5, 104, 104, 113, 122.46, 68, 47.8, 41.2, 83.6, 40.40, 77, 65.5, 66.0, 56.0, 125, 112, 37.8, 66.0, 56.0, 33.9, 56.0, 66.0, 100.5, 104, 100.5, 47.8, 66.0, 66.0, 66.0, 33.9, 72.1, 87.5, 66.0, 89.8, 89.8, 37.8, 47.8, 89.8, 83.6, 66.0, 37.8, 79.2, 33.9, 37.8, 37.8, 33.9, 5.33, 2.58, 38.4, 27.82, 11.63, 27.82, 61.7, 5.33, 5.33, 47.5, 9.7, 56.0, 37.8, 27.82, 5.333, 89.8, 72.1, 56.0, 86.3, 72.1, 83.6, 56.0, 27.82, 47.8, 56.0, 47.8, 37.8, 37.8, 56.0, 89.8, 23.03, 23.03, 56.0, 56.0, 47.8, 72.1, 47.8, 82.8, 97.2, 37.8, 83.6, 64.4, 83.6, 47.8, 37.8, 2.58, 79.2, 56.0, 61.6, 89.8, 37.8, 37.8, 37.8, 27.82, 33.9, 37.8, 306)
fossil_clade_taxa <- c("Acalypha", "Ginkgo", "Amborella", "Acalypha", "Nymphaea", "Brasenia", "Trimenia", "Kadsura", "Hedyosmum", "Sarcandra", "Sarcandra", "Chloranthus", "Canella", "Tasmannia", "Lactoris", "Aristolochia", "Saururus", "Anemopsis", "Magnolia", "Annona", "Eupomatia", "Annona", "Hedycarya", "Idiospermum", "Hedycarya", "Cryptocarya", "Acorus", "Zea", "Spathiphyllum", "Xanthosoma", "Alisma", "Hydrocharis", "Carludovica", "Croomia", "Lilium", "Smilax", "Canna", "Chamaedorea", "Pontederia", "Anigozanthos", "Tradescantia", "Canna", "Sparganium", "Puya", "Restio", "Centrolepis", "Joinvillea", "Zea", "Ceratophyllum", "Acalypha", "Euptelea", "Caulophyllum", "Kingdonia", "Akebia", "Menispermum", "Caulophyllum", "Cocculus", "Cissampelos", "Mahonia", "Caulophyllum", "Hydrastis", "Ranunculus", "Sabia", "Meliosma", "Nelumbo", "Grevillea", "Platanus", "Grevillea", "Dillenia", "Acalypha", "Dillenia", "Tetracera", "Heisteria", "Acalypha", "Gaiadendron", "Misodendrum", "Fagopyrum", "Plumbago", "Celosia", "Stellaria", "Bougainvillea", "Sarcobatus", "Nyssa", "Petalonyx", "Nyssa", "Alangium", "Fendlera", "Petalonyx", "Marcgravia", "Rhododendron", "Phlox", "Cobaea", "Galax", "Halesia", "Sarracenia", "Rhododendron", "Roridula", "Actinidia", "Icacina", "Vahlia", "Eucommia", "Aucuba", "Vahlia", "Mazus", "Ipomoea", "Nicotiana", "Luculia", "Mitchella", "Nerium", "Exacum", "Exacum", "Gentiana", "Antirrhinum", "Plantago", "Harpagophytum", "Sesamum", "Campsis", "Catalpa", "Nelsonia", "Barleria", "Paulownia", "Rehmannia", "Lamium", "Callicarpa", "Ilex", "Helwingia", "Pseudonemacladus", "Campanula", "Nymphoides", "Menyanthes", "Boopis", "Helianthus", "Boopis", "Moschopsis", "Aralidium", "Melanophylla", "Hydrocotyle", "Tetrapanax", "Weigela", "Diervilla", "Patrinia", "Valeriana", "Choristylis", "Haloragis", "Haloragis", "Penthorum", "Vitis", "Leea", "Terminalia", "Clarkia", "Lythrum", "Clarkia", "Qualea", "Myrtus", "Heteropyxis", "Myrtus", "Staphylea", "Crossosoma", "Bursera", "Rhus", "Cupaniopsis", "Aesculus", "Trichilia", "Swietenia", "Tapiscia", "Perrottetia", "Neurada", "Sterculia", "Thymelaea", "Sterculia", "Neurada", "Brassica", "Arabidopsis", "Brassica", "Krameria", "Larrea", "Stylobasium", "Schotia", "Lotus", "Mimosa", "Spiraea", "Photinia", "Elaeagnus", "Ceanothus", "Rhamnus", "Ceanothus", "Nothofagus", "Morella", "Fagus", "Morella", "Fagus", "Chrysolepis", "Casuarina", "Morella", "Juglans", "Morella", "Casuarina", "Alnus", "Tetrameles", "Coccinia", "Siphonodon", "Brexia", "Tripterygium", "Celastrus", "Cephalotus", "Davidsonia", "Eucryphia", "Davidsonia", "Sloanea", "Crinodendron", "Symphonia", "Cratoxylum", "Idesia", "Populus", "Salix", "Populus", "Elatine", "Malpighia", "Tetrapterys", "Malpighia", "Rhizophora", "Carallia", "Pimelodendron", "Acalypha", "Ginkgo", "Taxus")

###

min_constraints_clade <- vector("list", length(fossil_clade_taxa))
for (i in seq(1, length(fossil_clade_taxa), 2)){
min_constraints_clade[[i]] <- c(fossil_clade_taxa[[i]], fossil_clade_taxa[[i+1]])
}

removal <- vector(mode="numeric", length=0)
for (i in 1:length(min_constraints_clade)){
if (length(min_constraints_clade[[i]]) < 1){
removal <- append(removal, i)
}
}
min_constraints_clade <- min_constraints_clade[-removal]
